name: Docker Compose Test

on:
  pull_request:
    branches:
      - main

jobs:
  compose-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build containers
        run: docker compose build

      - name: Run containers
        run: docker compose up -d

      - name: Wait for services
        run: sleep 15

      - name: Network test
        run: curl -f http://localhost:8080 || exit 1

      - name: Show running containers
        run: docker ps

      - name: Show Container Logs
        if: always()
        run: docker compose logs

      - name: Tear Down Docker Compose Stack
        if: always()
        run: docker compose down
